# Generated by Django 3.2.25 on 2025-07-15 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voetbalspelers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('actuele_club', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('datum_invoer', models.DateTimeField(default=django.utils.timezone.now)),
                ('datum_laatste_aanpassing', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
